# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast playlists 💽
docs: true
docsurl: https://radio-aktywne.github.io/pelican
email: it@radioaktywne.pl
envprefix: PELICAN
events: true
imagename: services/pelican
importname: pelican
port: 42000
registry: true
releases: true
reponame: pelican
repourl: https://github.com/radio-aktywne/pelican
servicename: pelican
sse: true
