# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast playlists 💽
docs: true
docsurl: https://radio-aktywne.github.io/emitunes
email: it@radioaktywne.pl
envprefix: EMITUNES
events: true
imagename: services/emitunes
importname: emitunes
port: 42000
registry: true
releases: true
reponame: emitunes
repourl: https://github.com/radio-aktywne/emitunes
servicename: emitunes
sse: true
