services:
  pelican:
    build:
      context: ./
      network: host
    environment:
      - "PELICAN__SERVER__HOST=${PELICAN__SERVER__HOST:-0.0.0.0}"
      - "PELICAN__SERVER__PORT=${PELICAN__SERVER__PORT:-10200}"
      - "PELICAN__SERVER__TRUSTED=${PELICAN__SERVER__TRUSTED:-*}"
      - "PELICAN__GRAPHITE__SQL__HOST=${PELICAN__GRAPHITE__SQL__HOST:-localhost}"
      - "PELICAN__GRAPHITE__SQL__PORT=${PELICAN__GRAPHITE__SQL__PORT:-10220}"
      - "PELICAN__GRAPHITE__SQL__PASSWORD=${PELICAN__GRAPHITE__SQL__PASSWORD:-password}"
      - "PELICAN__MINIUM__S3__SECURE=${PELICAN__MINIUM__S3__SECURE:-false}"
      - "PELICAN__MINIUM__S3__HOST=${PELICAN__MINIUM__S3__HOST:-localhost}"
      - "PELICAN__MINIUM__S3__PORT=${PELICAN__MINIUM__S3__PORT:-10210}"
      - "PELICAN__MINIUM__S3__USER=${PELICAN__MINIUM__S3__USER:-readwrite}"
      - "PELICAN__MINIUM__S3__PASSWORD=${PELICAN__MINIUM__S3__PASSWORD:-password}"
      - "PELICAN__DEBUG=${PELICAN__DEBUG:-true}"
    network_mode: host
